
import numpy as np

class IndexFlatIP:
    d: int
    ntotal: int

    def __init__(self, d: int) -> None: ...
    def add(self, x: np.ndarray) -> None: ...
    def search(self, x: np.ndarray, k: int) -> tuple[np.ndarray, np.ndarray]: ...


def write_index(index: IndexFlatIP, filename: str) -> None: ...

def read_index(filename: str) -> IndexFlatIP: ...
